-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 15:35:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UnitinsSalas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UnitinsSalas` ;

-- -----------------------------------------------------
-- Schema UnitinsSalas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UnitinsSalas` DEFAULT CHARACTER SET utf8 ;
USE `UnitinsSalas` ;

-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwServidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwServidor` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwServidor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Matricula` VARCHAR(45) NOT NULL,
  `Ativo` TINYINT(1) NOT NULL,
  `Docente` TINYINT(1) NOT NULL,
  `Cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Unidade` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Unidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Cep` INT NOT NULL,
  `Latitude` FLOAT NULL,
  `Longitude` FLOAT NULL,
  `Ativo` TINYINT(1) NOT NULL,
  `DiretorGeral` INT NOT NULL,
  `Administrador` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_unidade_vwServidores1_idx` (`DiretorGeral` ASC),
  INDEX `fk_unidade_vwServidores2_idx` (`Administrador` ASC),
  CONSTRAINT `fk_unidade_vwServidores1`
    FOREIGN KEY (`DiretorGeral`)
    REFERENCES `UnitinsSalas`.`VwServidor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_vwServidores2`
    FOREIGN KEY (`Administrador`)
    REFERENCES `UnitinsSalas`.`VwServidor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Predio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Predio` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Predio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Pisos` INT NOT NULL,
  `Unidade` INT NULL,
  `Ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_predio_unidade1_idx` (`Unidade` ASC),
  CONSTRAINT `fk_predio_unidade1`
    FOREIGN KEY (`Unidade`)
    REFERENCES `UnitinsSalas`.`Unidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Entidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Entidade` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Entidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Registro` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Registro` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdPai` INT NULL,
  `IdEntidade` INT NOT NULL,
  `Descricao` VARCHAR(50) NOT NULL,
  `Ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_registros_registros_idx` (`IdPai` ASC),
  INDEX `fk_registros_entidade1_idx` (`IdEntidade` ASC),
  CONSTRAINT `fk_registros_registros`
    FOREIGN KEY (`IdPai`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registros_entidade1`
    FOREIGN KEY (`IdEntidade`)
    REFERENCES `UnitinsSalas`.`Entidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Sala` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Sala` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(200) NOT NULL,
  `Piso` INT NOT NULL,
  `Predio` INT NULL,
  `Tipo` INT NOT NULL,
  `Ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_salas_bloco1_idx` (`Predio` ASC),
  INDEX `fk_salas_registros1_idx` (`Tipo` ASC),
  CONSTRAINT `fk_salas_bloco1`
    FOREIGN KEY (`Predio`)
    REFERENCES `UnitinsSalas`.`Predio` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salas_registros1`
    FOREIGN KEY (`Tipo`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwSemestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwSemestre` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwSemestre` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`RecursosSalas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`RecursosSalas` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`RecursosSalas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Registro` INT NOT NULL,
  `Sala` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_registros_has_sala_sala1_idx` (`Sala` ASC),
  INDEX `fk_registros_has_sala_registros1_idx` (`Registro` ASC),
  CONSTRAINT `fk_registros_has_sala_registros1`
    FOREIGN KEY (`Registro`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registros_has_sala_sala1`
    FOREIGN KEY (`Sala`)
    REFERENCES `UnitinsSalas`.`Sala` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwCurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwCurso` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwCurso` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(45) NOT NULL,
  `Unidade` INT NULL,
  `CodCurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_vwCurso_unidade1_idx` (`Unidade` ASC),
  CONSTRAINT `fk_vwCurso_unidade1`
    FOREIGN KEY (`Unidade`)
    REFERENCES `UnitinsSalas`.`Unidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`SemestreLetivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`SemestreLetivo` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`SemestreLetivo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Semestre` INT NOT NULL,
  `Curso` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_alocacao_semestreLetivo1_idx` (`Semestre` ASC),
  INDEX `fk_alocacao_vwCurso1_idx` (`Curso` ASC),
  CONSTRAINT `fk_alocacao_semestreLetivo1`
    FOREIGN KEY (`Semestre`)
    REFERENCES `UnitinsSalas`.`VwSemestre` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alocacao_vwCurso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `UnitinsSalas`.`VwCurso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwDisciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwDisciplina` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwDisciplina` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Periodo` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `CodCurricular` INT NOT NULL,
  `Curso` INT NULL,
  `PreRequesito` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_vwDisciplina_vwCurso1_idx` (`Curso` ASC),
  INDEX `fk_vwDisciplina_vwDisciplina1_idx` (`PreRequesito` ASC),
  CONSTRAINT `fk_vwDisciplina_vwCurso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `UnitinsSalas`.`VwCurso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vwDisciplina_vwDisciplina1`
    FOREIGN KEY (`PreRequesito`)
    REFERENCES `UnitinsSalas`.`VwDisciplina` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Oferta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodPeriodoletivo` VARCHAR(50) NULL,
  `CodTurma` VARCHAR(50) NULL,
  `NomeTurma` VARCHAR(100) NULL,
  `Contexto` VARCHAR(50) NULL,
  `Curso` INT NULL,
  `DiaSemana` INT NULL,
  `Periodo` INT NULL,
  `Disciplina` VARCHAR(200) NULL,
  `DescricaoPeriodoLetivo` VARCHAR(100) NULL,
  `HoraInicialA` VARCHAR(6) NULL,
  `HoraInicialB` VARCHAR(6) NULL,
  `IntervaloInicio` VARCHAR(6) NULL,
  `HoraFinalA` VARCHAR(6) NULL,
  `HoraFinalB` VARCHAR(6) CHARACTER SET 'big5' COLLATE 'big5_chinese_ci' NULL,
  `IntervaloFinal` VARCHAR(6) NULL,
  `ProfessorTitular` VARCHAR(100) NULL,
  `TipoProfessor` VARCHAR(2) NULL,
  `Turno` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Oferta_VwCurso1_idx` (`Curso` ASC),
  INDEX `fk_Oferta_Registro1_idx` (`DiaSemana` ASC),
  INDEX `fk_Oferta_Registro2_idx` (`Turno` ASC),
  CONSTRAINT `fk_Oferta_VwCurso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `UnitinsSalas`.`VwCurso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Registro1`
    FOREIGN KEY (`DiaSemana`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Registro2`
    FOREIGN KEY (`Turno`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`AlocacaoSala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`AlocacaoSala` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`AlocacaoSala` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Semestre` INT NOT NULL,
  `Sala` INT NOT NULL,
  `Oferta` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_alocacao_has_sala_sala1_idx` (`Sala` ASC),
  INDEX `fk_AlocacaoSala_SemestreLetivo1_idx` (`Semestre` ASC),
  INDEX `fk_AlocacaoSala_Oferta1_idx` (`Oferta` ASC),
  CONSTRAINT `fk_alocacao_has_sala_sala1`
    FOREIGN KEY (`Sala`)
    REFERENCES `UnitinsSalas`.`Sala` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlocacaoSala_SemestreLetivo1`
    FOREIGN KEY (`Semestre`)
    REFERENCES `UnitinsSalas`.`SemestreLetivo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlocacaoSala_Oferta1`
    FOREIGN KEY (`Oferta`)
    REFERENCES `UnitinsSalas`.`Oferta` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`TurmaProfessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`TurmaProfessor` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`TurmaProfessor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `AlocacaoSala` INT NOT NULL,
  `Professor` INT NOT NULL,
  `SemestreLetivo` INT NOT NULL,
  INDEX `fk_alocacaoSalas_has_vwServidores_vwServidores1_idx` (`Professor` ASC),
  INDEX `fk_alocacaoSalas_has_vwServidores_alocacaoSalas1_idx` (`AlocacaoSala` ASC),
  PRIMARY KEY (`Id`),
  INDEX `fk_TurmaProfessor_SemestreLetivo1_idx` (`SemestreLetivo` ASC),
  CONSTRAINT `fk_alocacaoSalas_has_vwServidores_alocacaoSalas1`
    FOREIGN KEY (`AlocacaoSala`)
    REFERENCES `UnitinsSalas`.`AlocacaoSala` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alocacaoSalas_has_vwServidores_vwServidores1`
    FOREIGN KEY (`Professor`)
    REFERENCES `UnitinsSalas`.`VwServidor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TurmaProfessor_SemestreLetivo1`
    FOREIGN KEY (`SemestreLetivo`)
    REFERENCES `UnitinsSalas`.`SemestreLetivo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Horarios` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Horarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Inicio` TIME NOT NULL,
  `Fim` TIME NOT NULL,
  `Turno` INT NOT NULL,
  `Semestre` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Horarios_registros1_idx` (`Turno` ASC),
  INDEX `fk_Horarios_semestre1_idx` (`Semestre` ASC),
  CONSTRAINT `fk_Horarios_registros1`
    FOREIGN KEY (`Turno`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_semestre1`
    FOREIGN KEY (`Semestre`)
    REFERENCES `UnitinsSalas`.`VwSemestre` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwAluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwAluno` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwAluno` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Matricula` VARCHAR(45) NOT NULL,
  `Curso` INT NOT NULL,
  `Cpf` VARCHAR(20) NULL,
  `Senha` VARCHAR(256) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_VwAluno_VwCurso1_idx` (`Curso` ASC),
  CONSTRAINT `fk_VwAluno_VwCurso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `UnitinsSalas`.`VwCurso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`VwMatricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`VwMatricula` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`VwMatricula` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdDisciplina` INT NOT NULL,
  `IdAluno` INT NOT NULL,
  `IdSemestreLetivo` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_VwDisciplina_has_VwAluno_VwAluno1_idx` (`IdAluno` ASC),
  INDEX `fk_VwDisciplina_has_VwAluno_VwDisciplina1_idx` (`IdDisciplina` ASC),
  INDEX `fk_VwMatricula_SemestreLetivo1_idx` (`IdSemestreLetivo` ASC),
  CONSTRAINT `fk_VwDisciplina_has_VwAluno_VwDisciplina1`
    FOREIGN KEY (`IdDisciplina`)
    REFERENCES `UnitinsSalas`.`VwDisciplina` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VwDisciplina_has_VwAluno_VwAluno1`
    FOREIGN KEY (`IdAluno`)
    REFERENCES `UnitinsSalas`.`VwAluno` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VwMatricula_SemestreLetivo1`
    FOREIGN KEY (`IdSemestreLetivo`)
    REFERENCES `UnitinsSalas`.`SemestreLetivo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`TurnoHorarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`TurnoHorarios` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`TurnoHorarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Turno` INT NOT NULL,
  `HoraAinicio` VARCHAR(10) NOT NULL,
  `HoraAfim` VARCHAR(10) NOT NULL,
  `HoraBinicio` VARCHAR(10) NOT NULL,
  `HoraBfim` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_TurnoHorario_Registro1_idx` (`Turno` ASC),
  CONSTRAINT `fk_TurnoHorario_Registro1`
    FOREIGN KEY (`Turno`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnitinsSalas`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnitinsSalas`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `UnitinsSalas`.`Laboratorio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Observacao` VARCHAR(1000) NULL,
  `Semestre` INT NOT NULL,
  `Laboratorio` INT NOT NULL,
  `TipoUso` INT NOT NULL,
  `Turno` INT NULL,
  `Dia` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Laboratorio_Sala1_idx` (`Laboratorio` ASC),
  INDEX `fk_Laboratorio_Registro1_idx` (`TipoUso` ASC),
  INDEX `fk_Laboratorio_Registro2_idx` (`Turno` ASC),
  INDEX `fk_Laboratorio_Registro3_idx` (`Dia` ASC),
  INDEX `fk_Laboratorio_VwSemestre1_idx` (`Semestre` ASC),
  CONSTRAINT `fk_Laboratorio_Sala1`
    FOREIGN KEY (`Laboratorio`)
    REFERENCES `UnitinsSalas`.`Sala` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratorio_Registro1`
    FOREIGN KEY (`TipoUso`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratorio_Registro2`
    FOREIGN KEY (`Turno`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratorio_Registro3`
    FOREIGN KEY (`Dia`)
    REFERENCES `UnitinsSalas`.`Registro` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Laboratorio_VwSemestre1`
    FOREIGN KEY (`Semestre`)
    REFERENCES `UnitinsSalas`.`VwSemestre` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
